import type { MemeItem, MemeCategory } from "./types";

export const MEME_CATEGORIES: MemeCategory[] = [
  "All",
  "Trending",
  "Reaction",
  "Work",
  "Anime",
  "Gaming",
  "Success",
  "Funny",
  "Sad",
  "Angry",
  "Happy",
  "Confused",
  "Celebration",
];

export const CURATED_MEMES: MemeItem[] = [];

export const CURATED_GIFS: MemeItem[] = [
  {
    id: "gif-this-is-fine",
    title: "This Is Fine Dog",
    url: "https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif",
    type: "gif",
    category: "Work",
    tags: ["this is fine", "fire", "dog", "work", "deadline", "stress", "coding", "debugging", "chaos"],
    animated: true,
    aspectRatio: 1.33,
  },
  {
    id: "gif-leonardo-cheers",
    title: "Leo Gatsby Cheers Toast",
    url: "https://media.giphy.com/media/g9582DNuQppxC/giphy.gif",
    type: "gif",
    category: "Success",
    tags: ["cheers", "celebration", "gatsby", "leonardo", "success", "win", "toast"],
    animated: true,
    aspectRatio: 1.77,
  },
  {
    id: "gif-mind-blown",
    title: "Mind Blown Galaxy",
    url: "https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif",
    type: "gif",
    category: "Reaction",
    tags: ["mind blown", "shocked", "galaxy", "wow", "amazing", "eureka", "idea"],
    animated: true,
    aspectRatio: 1.33,
  },
  {
    id: "gif-cat-typing-fast",
    title: "Cat Hacking & Typing Fast",
    url: "https://media.giphy.com/media/unQ3IJU2RG7DO/giphy.gif",
    type: "gif",
    category: "Work",
    tags: ["cat", "typing", "coding", "work", "deadline", "fast", "hacker", "programmer"],
    animated: true,
    aspectRatio: 1.33,
  },
  {
    id: "gif-confused-travolta",
    title: "Confused Vincent Vega",
    url: "https://media.giphy.com/media/g01ZnwAUvutuK8GIQn/giphy.gif",
    type: "gif",
    category: "Confused",
    tags: ["confused", "travolta", "pulp fiction", "looking around", "lost", "where"],
    animated: true,
    aspectRatio: 1.77,
  },
  {
    id: "gif-steve-carell-no",
    title: "Michael Scott NO GOD PLEASE NO",
    url: "https://media.giphy.com/media/vyTnNTrs3wqQ0UIvwE/giphy.gif",
    type: "gif",
    category: "Angry",
    tags: ["no", "screaming", "angry", "god please no", "office", "fail", "bug"],
    animated: true,
    aspectRatio: 1.77,
  },
  {
    id: "gif-clap-applause",
    title: "Standing Ovation & Applause",
    url: "https://media.giphy.com/media/7rj2ZgttvgomY/giphy.gif",
    type: "gif",
    category: "Celebration",
    tags: ["applause", "clap", "great job", "bravo", "win", "respect", "crowd"],
    animated: true,
    aspectRatio: 1.77,
  },
  {
    id: "gif-popcorn-eating",
    title: "Eating Popcorn Watching Drama",
    url: "https://media.giphy.com/media/hVTouq08miyGT52UKL/giphy.gif",
    type: "gif",
    category: "Trending",
    tags: ["popcorn", "drama", "watching", "entertaining", "snack", "fun"],
    animated: true,
    aspectRatio: 1.33,
  },
  {
    id: "gif-excited-kermit",
    title: "Kermit Yay Flail",
    url: "https://media.giphy.com/media/DPznISmq0hLRRI2ERU/giphy.gif",
    type: "gif",
    category: "Happy",
    tags: ["kermit", "excited", "happy", "yay", "arms", "celebration"],
    animated: true,
    aspectRatio: 1.33,
  },
  {
    id: "gif-developer-coffee",
    title: "Need More Coffee",
    url: "https://media.giphy.com/media/3oKIPnAiaMCws8nOsE/giphy.gif",
    type: "gif",
    category: "Work",
    tags: ["coffee", "morning", "caffeine", "tired", "developer", "working"],
    animated: true,
    aspectRatio: 1.33,
  },
  {
    id: "gif-shocked-cat",
    title: "Shocked Cat Eyes",
    url: "https://media.giphy.com/media/mlvseq9yvZhba/giphy.gif",
    type: "gif",
    category: "Reaction",
    tags: ["cat", "shocked", "eyes", "omg", "unbelievable", "surprised"],
    animated: true,
    aspectRatio: 1.33,
  },
  {
    id: "gif-happy-dance-snoopy",
    title: "Snoopy Happy Dance",
    url: "https://media.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif",
    type: "gif",
    category: "Happy",
    tags: ["happy", "dance", "celebrate", "snoopy", "joy", "cheerful", "fun"],
    animated: true,
    aspectRatio: 1.33,
  },
  {
    id: "gif-nodding-agree",
    title: "Jeremiah Johnson Nodding",
    url: "https://media.giphy.com/media/gOkawaguYNi539RZfl/giphy.gif",
    type: "gif",
    category: "Reaction",
    tags: ["nod", "agree", "yes", "approval", "respect", "manly nod"],
    animated: true,
    aspectRatio: 1.33,
  },
  {
    id: "gif-office-parkour",
    title: "Michael Scott Parkour",
    url: "https://media.giphy.com/media/DoCIC5RIQOcxx528v3/giphy.gif",
    type: "gif",
    category: "Trending",
    tags: ["parkour", "office", "michael scott", "agility", "pivot", "startup"],
    animated: true,
    aspectRatio: 1.77,
  },
];

export const CURATED_STICKERS: MemeItem[] = [
  {
    id: "stk-fire",
    title: "Lit Flame Fire",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f525.svg",
    type: "sticker",
    category: "Reaction",
    tags: ["fire", "hot", "lit", "trending", "hype", "cool"],
  },
  {
    id: "stk-rocket",
    title: "Rocket Launch",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f680.svg",
    type: "sticker",
    category: "Celebration",
    tags: ["rocket", "launch", "ship", "startup", "growth", "fast"],
  },
  {
    id: "stk-sparkles",
    title: "Magic Sparkles",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/2728.svg",
    type: "sticker",
    category: "Reaction",
    tags: ["sparkles", "magic", "shine", "clean", "new", "gold"],
  },
  {
    id: "stk-hundred",
    title: "100 Points Fact",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f4af.svg",
    type: "sticker",
    category: "Success",
    tags: ["100", "score", "perfect", "fact", "real", "win"],
  },
  {
    id: "stk-party",
    title: "Party Popper Confetti",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f389.svg",
    type: "sticker",
    category: "Celebration",
    tags: ["party", "celebration", "confetti", "birthday", "congrats"],
  },
  {
    id: "stk-trophy",
    title: "Golden Trophy",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f3c6.svg",
    type: "sticker",
    category: "Success",
    tags: ["trophy", "winner", "champion", "gold", "number 1"],
  },
  {
    id: "stk-sunglasses",
    title: "Cool Sunglasses Face",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f60e.svg",
    type: "sticker",
    category: "Funny",
    tags: ["cool", "sunglasses", "swag", "boss", "confident"],
  },
  {
    id: "stk-laughing",
    title: "Rolling On Floor Laughing",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f923.svg",
    type: "sticker",
    category: "Funny",
    tags: ["rofl", "laugh", "funny", "hilarious", "lol"],
  },
  {
    id: "stk-mindblown",
    title: "Exploding Head Mind Blown",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f92f.svg",
    type: "sticker",
    category: "Reaction",
    tags: ["exploding head", "mind blown", "shocked", "wow"],
  },
  {
    id: "stk-gaming-controller",
    title: "Video Game Controller",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f3ae.svg",
    type: "sticker",
    category: "Gaming",
    tags: ["game", "controller", "gaming", "play", "joystick"],
  },
  {
    id: "stk-laptop-code",
    title: "Laptop Developer Work",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f4bb.svg",
    type: "sticker",
    category: "Work",
    tags: ["laptop", "computer", "code", "work", "tech", "software"],
  },
  {
    id: "stk-warning",
    title: "Warning Alert",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/26a0.svg",
    type: "sticker",
    category: "Reaction",
    tags: ["warning", "alert", "danger", "caution", "bug", "error"],
  },
  {
    id: "stk-heart-eyes",
    title: "Heart Eyes Love",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f60d.svg",
    type: "sticker",
    category: "Happy",
    tags: ["heart eyes", "love", "awesome", "adore", "crush"],
  },
  {
    id: "stk-thumbs-up",
    title: "Thumbs Up Approval",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f44d.svg",
    type: "sticker",
    category: "Success",
    tags: ["thumbs up", "good", "yes", "approve", "ok", "great"],
  },
  {
    id: "stk-clapping",
    title: "Clapping Hands Applause",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f44f.svg",
    type: "sticker",
    category: "Celebration",
    tags: ["clap", "applause", "bravo", "great job", "congrats"],
  },
  {
    id: "stk-raising-hands",
    title: "Raising Hands Praise",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f64c.svg",
    type: "sticker",
    category: "Celebration",
    tags: ["praise", "celebrate", "hands", "hooray", "cheer"],
  },
  {
    id: "stk-biceps",
    title: "Strong Flexed Biceps",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f4aa.svg",
    type: "sticker",
    category: "Success",
    tags: ["muscle", "flex", "strong", "power", "fitness", "workout"],
  },
  {
    id: "stk-thinking",
    title: "Thinking Questioning Face",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f914.svg",
    type: "sticker",
    category: "Confused",
    tags: ["thinking", "hmm", "question", "ponder", "wonder"],
  },
  {
    id: "stk-crown",
    title: "Golden Royal Crown",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f451.svg",
    type: "sticker",
    category: "Success",
    tags: ["crown", "king", "queen", "royal", "winner", "vip", "gold"],
  },
  {
    id: "stk-money-bag",
    title: "Money Dollar Bag",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f4b0.svg",
    type: "sticker",
    category: "Success",
    tags: ["money", "cash", "dollars", "wealth", "revenue", "rich"],
  },
  {
    id: "stk-cash-wings",
    title: "Flying Cash Wings",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f4b8.svg",
    type: "sticker",
    category: "Success",
    tags: ["money", "cash", "spend", "flying", "loss", "crypto"],
  },
  {
    id: "stk-diamond",
    title: "Sparkling Diamond Gem",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f48e.svg",
    type: "sticker",
    category: "Success",
    tags: ["diamond", "gem", "rare", "shiny", "precious", "hands"],
  },
  {
    id: "stk-lightbulb",
    title: "Light Bulb Bright Idea",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f4a1.svg",
    type: "sticker",
    category: "Work",
    tags: ["idea", "lightbulb", "eureka", "smart", "solution", "inspiration"],
  },
  {
    id: "stk-target",
    title: "Bullseye Direct Target",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f3af.svg",
    type: "sticker",
    category: "Success",
    tags: ["target", "bullseye", "goal", "accurate", "focus", "hit"],
  },
  {
    id: "stk-eyes",
    title: "Sneaky Looking Eyes",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f440.svg",
    type: "sticker",
    category: "Reaction",
    tags: ["eyes", "look", "watching", "sneaky", "curious", "see"],
  },
  {
    id: "stk-star-struck",
    title: "Star Struck Grin",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f929.svg",
    type: "sticker",
    category: "Happy",
    tags: ["star", "amazed", "star struck", "wow", "fan", "excited"],
  },
  {
    id: "stk-party-face",
    title: "Party Horn Celebration Face",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f973.svg",
    type: "sticker",
    category: "Celebration",
    tags: ["party", "celebrate", "birthday", "festive", "fun", "cheer"],
  },
  {
    id: "stk-tears-joy",
    title: "Tears of Joy Laughing",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f602.svg",
    type: "sticker",
    category: "Funny",
    tags: ["laugh", "tears", "joy", "funny", "hilarious", "crying laugh"],
  },
  {
    id: "stk-crying-loudly",
    title: "Loud Crying Tears",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f62d.svg",
    type: "sticker",
    category: "Sad",
    tags: ["crying", "tears", "sad", "emotional", "loud", "drama"],
  },
  {
    id: "stk-screaming-fear",
    title: "Shocked Screaming Face",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f631.svg",
    type: "sticker",
    category: "Reaction",
    tags: ["scream", "shocked", "fear", "omg", "panic", "unbelievable"],
  },
  {
    id: "stk-nerd-face",
    title: "Nerd Geek Glasses",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f913.svg",
    type: "sticker",
    category: "Work",
    tags: ["nerd", "geek", "glasses", "smart", "coding", "technician"],
  },
  {
    id: "stk-alien-retro",
    title: "Retro Arcade Space Invader",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f47e.svg",
    type: "sticker",
    category: "Gaming",
    tags: ["arcade", "alien", "retro", "pixel", "gaming", "space invaders"],
  },
  {
    id: "stk-ghost",
    title: "Playful Ghost",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f47b.svg",
    type: "sticker",
    category: "Anime",
    tags: ["ghost", "spooky", "boo", "cute", "halloween"],
  },
  {
    id: "stk-siren",
    title: "Emergency Alert Siren",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f6a8.svg",
    type: "sticker",
    category: "Reaction",
    tags: ["siren", "police", "alert", "emergency", "urgent", "breaking"],
  },
  {
    id: "stk-check-mark",
    title: "Green Check Mark Completed",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/2705.svg",
    type: "sticker",
    category: "Success",
    tags: ["check", "done", "completed", "success", "verified", "true"],
  },
  {
    id: "stk-collision-pow",
    title: "Comic Boom POW Collision",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f4a5.svg",
    type: "sticker",
    category: "Reaction",
    tags: ["boom", "collision", "pow", "explosion", "impact", "drama"],
  },
  {
    id: "stk-medal-first",
    title: "First Place 1st Gold Medal",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f947.svg",
    type: "sticker",
    category: "Success",
    tags: ["medal", "first place", "gold", "winner", "champion", "award"],
  },
  {
    id: "stk-popcorn",
    title: "Movie Theater Popcorn",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f37f.svg",
    type: "sticker",
    category: "Trending",
    tags: ["popcorn", "movie", "drama", "snack", "watching", "film"],
  },
  {
    id: "stk-coffee",
    title: "Hot Steaming Coffee Mug",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/2615.svg",
    type: "sticker",
    category: "Work",
    tags: ["coffee", "tea", "mug", "caffeine", "morning", "work", "break"],
  },
  {
    id: "stk-shushing",
    title: "Shushing Quiet Secret Face",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f92b.svg",
    type: "sticker",
    category: "Reaction",
    tags: ["shh", "quiet", "secret", "silent", "hush", "whisper"],
  },
  {
    id: "stk-peace-sign",
    title: "Victory Peace Hand Sign",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/270c.svg",
    type: "sticker",
    category: "Happy",
    tags: ["peace", "victory", "two", "cool", "hand", "chill"],
  },
  {
    id: "stk-beer-toast",
    title: "Clinking Beer Mugs Cheers",
    url: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f37b.svg",
    type: "sticker",
    category: "Celebration",
    tags: ["cheers", "beer", "toast", "drinks", "celebrate", "party"],
  },
];
